; Bank-word alignment gate for compiler-placed vector memory objects
; (RISCVFrameLowering.cpp, XMemorableBankWordBytes).
;
; THE HARDWARE CONTRACT.  The decode engine's vector data bank is an array of
; 64-byte WORDS and both vector-memory legs are single-word by construction:
; the load FU writes the addressed row's 512 bits straight into vd (rs1[5:0]
; never enters the path), and the store FU places its source words at rs1[5:0]
; INSIDE one word and drops everything past byte 63.  So a vector access whose
; base is not 64-byte aligned is architecturally illegal -- the RTL traps it at
; dispatch (dual_dispatch.sv's bank-word granularity guard, which names the
; offending byte slot).
;
; WHAT WENT WRONG.  The RVV stack section's minimum alignment is 16 bytes
; upstream.  The offsets handed out INSIDE that section are already whole-
; vector-register multiples, so every slot inherits the section base's
; alignment -- and a base only 16-byte aligned put an m4 spill 32 bytes into a
; bank word.  `vs4r.v v8,(s2)` with s2 = sp+288 then stored elements 0..7 and
; silently dropped 8..15, which belong in the NEXT word.
;
; The requirement is 64 bytes for EVERY LMUL, not LMUL * 64: the beat sequencer
; cracks a group into one-register beats and steps the scalar base by exactly
; one register (64 B) per beat, so a group is legal iff its BASE is word
; aligned.  All four LMULs are checked below for that reason.
;
; Each function here is the real failure shape: callee-saved registers above
; the RVV section whose size is not itself a multiple of 64, so the section
; base -- and with it every spill slot -- lands mid-word unless the frame is
; bank-word aligned.  Before the fix all four spilled to `sp + 16` on a frame
; of 32 + LMUL*64 bytes, i.e. 16 bytes into a bank word.
;
; NOTE llc, not %clang, and no autogenerated body: the release-gate lit config
; is a bare ShTest with no substitutions, the same contract as
; xmemorable-sched.ll and the generated tests in this directory.
;
; RUN: llc -mtriple=riscv64 -mattr=+m,+zve32f,+zvl512b,+xmemorable -O2 %s -o - \
; RUN:   | FileCheck %s
; RUN: llc -mtriple=riscv64 -mattr=+m,+zve32f,+zvl512b,+xmemorable -O2 \
; RUN:   -stop-after=prologepilog %s -o - | FileCheck --check-prefix=MIR %s
;
; The offsets are matched against an explicit enumeration of the multiples of
; 64 that fit these small frames rather than a single pinned constant: the
; claim under test is "bank-word aligned", not "exactly this frame layout", and
; an alternation says so without re-pinning on every unrelated frame change.
; Every value the pre-fix compiler emitted here (16, 32, 80, 144, 272, 528) is
; outside the set, so the gate is red before the fix and green after it.

declare void @sink()

; CHECK-LABEL: spill_m1:
; CHECK:       addi sp, sp, -{{(64|128|192|256|320|384|448|512|576|640|704|768|832|896|960|1024)}}
; CHECK:       addi sp, sp, -{{(64|128|192|256|320|384|448|512|576|640|704|768|832|896|960|1024)}}
; CHECK:       addi [[SLOT:a[0-9]+]], sp, {{(0|64|128|192|256|320|384|448|512|576|640|704|768|832|896|960|1024)}}
; CHECK:       vs1r.v {{v[0-9]+}}, ([[SLOT]])
; MIR-LABEL: name:            spill_m1
; MIR:       maxAlignment:    64
define void @spill_m1(ptr %p) nounwind vscale_range(8,8) {
  %v = load volatile <vscale x 2 x i32>, ptr %p
  call void @sink()
  call void asm sideeffect "", "~{v0},~{v1},~{v2},~{v3},~{v4},~{v5},~{v6},~{v7},~{v8},~{v9},~{v10},~{v11},~{v12},~{v13},~{v14},~{v15},~{v16},~{v17},~{v18},~{v19},~{v20},~{v21},~{v22},~{v23},~{v24},~{v25},~{v26},~{v27},~{v28},~{v29},~{v30},~{v31}"()
  store volatile <vscale x 2 x i32> %v, ptr %p
  ret void
}

; CHECK-LABEL: spill_m2:
; CHECK:       addi sp, sp, -{{(64|128|192|256|320|384|448|512|576|640|704|768|832|896|960|1024)}}
; CHECK:       addi sp, sp, -{{(64|128|192|256|320|384|448|512|576|640|704|768|832|896|960|1024)}}
; CHECK:       addi [[SLOT:a[0-9]+]], sp, {{(0|64|128|192|256|320|384|448|512|576|640|704|768|832|896|960|1024)}}
; CHECK:       vs2r.v {{v[0-9]+}}, ([[SLOT]])
; MIR-LABEL: name:            spill_m2
; MIR:       maxAlignment:    64
define void @spill_m2(ptr %p) nounwind vscale_range(8,8) {
  %v = load volatile <vscale x 4 x i32>, ptr %p
  call void @sink()
  call void asm sideeffect "", "~{v0},~{v1},~{v2},~{v3},~{v4},~{v5},~{v6},~{v7},~{v8},~{v9},~{v10},~{v11},~{v12},~{v13},~{v14},~{v15},~{v16},~{v17},~{v18},~{v19},~{v20},~{v21},~{v22},~{v23},~{v24},~{v25},~{v26},~{v27},~{v28},~{v29},~{v30},~{v31}"()
  store volatile <vscale x 4 x i32> %v, ptr %p
  ret void
}

; The reported shape: an m4 group spilled with a whole-register store.
; CHECK-LABEL: spill_m4:
; CHECK:       addi sp, sp, -{{(64|128|192|256|320|384|448|512|576|640|704|768|832|896|960|1024)}}
; CHECK:       addi sp, sp, -{{(64|128|192|256|320|384|448|512|576|640|704|768|832|896|960|1024)}}
; CHECK:       addi [[SLOT:a[0-9]+]], sp, {{(0|64|128|192|256|320|384|448|512|576|640|704|768|832|896|960|1024)}}
; CHECK:       vs4r.v {{v[0-9]+}}, ([[SLOT]])
; MIR-LABEL: name:            spill_m4
; MIR:       maxAlignment:    64
define void @spill_m4(ptr %p) nounwind vscale_range(8,8) {
  %v = load volatile <vscale x 8 x i32>, ptr %p
  call void @sink()
  call void asm sideeffect "", "~{v0},~{v1},~{v2},~{v3},~{v4},~{v5},~{v6},~{v7},~{v8},~{v9},~{v10},~{v11},~{v12},~{v13},~{v14},~{v15},~{v16},~{v17},~{v18},~{v19},~{v20},~{v21},~{v22},~{v23},~{v24},~{v25},~{v26},~{v27},~{v28},~{v29},~{v30},~{v31}"()
  store volatile <vscale x 8 x i32> %v, ptr %p
  ret void
}

; CHECK-LABEL: spill_m8:
; CHECK:       addi sp, sp, -{{(64|128|192|256|320|384|448|512|576|640|704|768|832|896|960|1024)}}
; CHECK:       addi sp, sp, -{{(64|128|192|256|320|384|448|512|576|640|704|768|832|896|960|1024)}}
; CHECK:       addi [[SLOT:a[0-9]+]], sp, {{(0|64|128|192|256|320|384|448|512|576|640|704|768|832|896|960|1024)}}
; CHECK:       vs8r.v {{v[0-9]+}}, ([[SLOT]])
; MIR-LABEL: name:            spill_m8
; MIR:       maxAlignment:    64
define void @spill_m8(ptr %p) nounwind vscale_range(8,8) {
  %v = load volatile <vscale x 16 x i32>, ptr %p
  call void @sink()
  call void asm sideeffect "", "~{v0},~{v1},~{v2},~{v3},~{v4},~{v5},~{v6},~{v7},~{v8},~{v9},~{v10},~{v11},~{v12},~{v13},~{v14},~{v15},~{v16},~{v17},~{v18},~{v19},~{v20},~{v21},~{v22},~{v23},~{v24},~{v25},~{v26},~{v27},~{v28},~{v29},~{v30},~{v31}"()
  store volatile <vscale x 16 x i32> %v, ptr %p
  ret void
}

; A scalable-vector LOCAL, not a spill: the same section, so the same
; guarantee has to hold for it.  The 40-byte scalar local is deliberately not
; a multiple of 64, so the RVV section base is only correct if the frame pads
; up to the bank word.  Before the fix this landed on `sp + 48` of a 320-byte
; frame -- 16 bytes into a bank word.
; CHECK-LABEL: rvv_local_after_scalar:
; CHECK:       addi sp, sp, -{{(64|128|192|256|320|384|448|512|576|640|704|768|832|896|960|1024)}}
; CHECK:       addi sp, sp, -{{(64|128|192|256|320|384|448|512|576|640|704|768|832|896|960|1024)}}
; CHECK:       addi [[SLOT:a[0-9]+]], sp, {{(0|64|128|192|256|320|384|448|512|576|640|704|768|832|896|960|1024)}}
; CHECK:       vs4r.v {{v[0-9]+}}, ([[SLOT]])
; MIR-LABEL: name:            rvv_local_after_scalar
; MIR:       maxAlignment:    64
define void @rvv_local_after_scalar(ptr %p) nounwind vscale_range(8,8) {
  %s = alloca [40 x i8], align 8
  %v = alloca <vscale x 8 x i32>, align 8
  call void @sink()
  %l = load volatile <vscale x 8 x i32>, ptr %p
  store volatile <vscale x 8 x i32> %l, ptr %v
  %r = load volatile <vscale x 8 x i32>, ptr %v
  store volatile <vscale x 8 x i32> %r, ptr %p
  store volatile i8 1, ptr %s
  ret void
}
